import { BookDrawerProvider } from "@/context/book-drawer-context";
import { DayJsProvider } from "@/lib/dayjs";
import { NextAuthProvider } from "@/lib/next-auth";
import { QueryProvider } from "@/lib/react-query";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Nunito_Sans } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

const nunito = Nunito_Sans({
  variable: "--font-nunito",
  display: "block",
  weight: ["400", "600"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="pt-br">
      <body className={`${nunito.variable} antialiased`}>
        <NextAuthProvider session={session}>
          <QueryProvider>
            <BookDrawerProvider>{children}</BookDrawerProvider>
          </QueryProvider>
          <DayJsProvider />
        </NextAuthProvider>
      </body>
    </html>
  );
}
