version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: my_db
    environment:
      - MYSQL_DATABASE=ignitecall
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  mysql-volume:
    driver: local
